### ISSUE TITLE
Make cscope command configurable

### ISSUE THREAD

**Issue by kerneis-anssi** [intel/Edk2Code#1]
Could you please make the cscope command configurable in the settings (for Linux)? It would allow people running VSCode from a flatpak using `flatpak-spawn cscope` to use host-installed cscope.

(I know the proper way to do it is DevContainers, but not everybody has them set up and it would ease testing the extension before investing in a more complex setup.)

**Comment by gapalomi** [comment]
Thanks for letting me know this requirement. It should be small change. I will add it in the following release.

**Comment by gapalomi** [comment]
This change has been implemented in 61df458428bb1460bfa424caf7448c3a905e8dca.
@kerneis-anssi, this its available in version 1.0.5. Let me know if this works for you.
