### ISSUE TITLE
[New Feature]Shortcut to add debugging information

### ISSUE THREAD

**Issue by PhoenixTan2** [intel/Edk2Code#2]
Hi,

Debugging information is very commonly used and entering it every time is a very cumbersome process, so I want a shortcut to quickly add debugging information to the functionality.

For example, when I press Shift+F1, the following code will be inserted into the code:
DEBUG ((DEBUG_INFO, "Function:%a() Line:%d (DEBUG HERE) \n", \_\_FUNCTION\_\_, \_\_LINE\_\_));

Thanks!

**Comment by PhoenixTan2** [comment]
Code completion might be better: 
type DEBUG -> DEBUG ((DEBUG_INFO, "Function:%a() Line:%d (DEBUG HERE) \n", \_\_FUNCTION\_\_, \_\_LINE\_\_));

**Comment by gapalomi** [comment]
Thanks @PhoenixTan2. VSCODE natively supports the insertion of snippets using key bidning: [https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization)

> You can also open the keybindings.json file from the Command Palette (Ctrl+Shift+P) with the Preferences: Open Keyboard Shortcuts (JSON) command

In you `keybindings.json` file you can add the suggested snipped as this:

```json
    {
        "key": "Shift+f1",
        "command": "editor.action.insertSnippet",
        "args": {
            "snippet": "DEBUG ((DEBUG_INFO, \"Function:%a() Line:%d (DEBUG HERE) \\n\", __FUNCTION__, __LINE__));"
        }
    },
```

A convenient way to integrate what you suggest could be to add it as code suggestion when you type your code. 
If you start typing `DEB` it could suggest `DEBUG ((DEBUG_INFO, "Function:%a() Line:%d (DEBUG HERE) \n", __FUNCTION__, __LINE__));`

Even better it could also suggest printing the previous assigned value to a variable based in your cursor position like:
```c
    case ((UINTN)(-1)):
      RowChange = ConsoleInfo->RowsPerScreen;
      DEBUG ((DEBUG_INFO, "Function:%a() Line:%d (RowChange = 0x%x) \n", __FUNCTION__, __LINE__, RowChange));
      break;
```
Let me know your comments.

**Comment by gapalomi** [comment]
Im closing this issue as the same functionality requested can be achieved using native key binding
