### ISSUE TITLE
Some inf files appear in both .ignore and cscope.files in ubuntu

### ISSUE THREAD

**Issue by cordaferrea** [intel/Edk2Code#3]
Sorry to disturb you.    

This plug-in is really great, but I find some infs appear **in both .ignore and cscope.files**.  
My test Environment is as follow:  
> OS:Ubuntu20.04  vscode: 1.87.2  
> cscope:  version 15.9

And I delete the .ignore file and .edkCode, rebuild the index database also reproduced that problem. 
 
I guess that caused by the $(basename).inf's basename is not equal its father's inf name.  Such as edk2/ArmPlatformPkg/PrePi/PeiUniCore.inf：  
![PeiUniCore .ignore](https://github.com/intel/Edk2Code/assets/105853932/1b8a1d51-26d1-4787-ab5d-bdc2308e799c)
![PeiUniCore cscope](https://github.com/intel/Edk2Code/assets/105853932/0470c1e3-6d9e-4328-be08-2c45c24e538c)

Best Regards,  
Eden

**Comment by gapalomi** [comment]
Thanks for taking the time to file the issue. The way to generate `.ignore` file is very naive.
1. list all the types of files (extension) in `cscope.files`
2. search for those extensions in all your workspace.
3. add to `.ignore` all the found files that didn't match with content of `cscope.files`

[I see an issue in the code](https://github.com/intel/Edk2Code/blob/main/src/contextState/cmds.ts#L639) where relative paths on `cscope.files` are not resolved before comparison like:
`c:\src\edk2\OvmfPkg\Include\..\Library\HardwareInfoLib\HardwareInfoTypesLib.h`
won't match with `c:\src\edk2\OvmfPkg\Library\HardwareInfoLib\HardwareInfoTypesLib.h`

I will add that fix in the following release but I'm not sure if that's the issue you are seeing. Can you confirm if your blurred path has some relative paths?

**Comment by cordaferrea** [comment]
Hi @gapalomi,    

Thanks a lot for your patience and explaination.   

I confirm my blurred path in `ubuntu20.04`, content of `cscope.files`  display absolute path with **\\**  like Windows11:    
![cscope files](https://github.com/intel/Edk2Code/assets/105853932/9fdf31a5-3d60-4ce2-8242-84d03811cf1e)

Since I'm in  linux, so I check the / and \ again, do as follow:  

1. Setting C/C++ Compile commands ui with `${workspaceFolder}/.edkCode/compile_commands.json`  at first,   
![compile_build](https://github.com/intel/Edk2Code/assets/105853932/e4cb682f-69fe-48ae-b07c-2f01519db659)

2. `Run rebuild index database`. The plug-in `notice the path is wrong`(Actually, **in linux / is right**), when click fix, will auto-convert into `\`, then Build data  loaded, ignore file generate, `and also contain the files in cscope.files`.  
![wrong](https://github.com/intel/Edk2Code/assets/105853932/bcadb3d3-51b8-4afe-99a6-8e5635782bab)
![auto](https://github.com/intel/Edk2Code/assets/105853932/0018dddc-6532-4a4b-9d3e-0854ca3c2a18)
![test](https://github.com/intel/Edk2Code/assets/105853932/26fbf7d1-238e-42ee-a313-2b81194afbd3)
![ROC](https://github.com/intel/Edk2Code/assets/105853932/f56dffef-4953-4b28-89fb-af1d0e06e537)


3. Again `Run rebuild inxdex database` , the plug-in `will not display any wrong`, directly display `Build data  loaded`.  However, I check the Compile commands ui  display errors:  
![PixPin_2024-03-26_15-37-12](https://github.com/intel/Edk2Code/assets/105853932/38d931b1-ef68-4104-b1b2-0cc976aee8dd) 

So I zip the whole project delete the .edkCode and .ignore, keep build files, `Run rebuild inxdex database` in the windows' vscode also reproduce.  

Best Regards,  
Eden

**Comment by gapalomi** [comment]
Thanks @cordaferrea, I think I'm able to reproduce the problem in my WSL. I will try to provide a solution in the following days.

**Comment by cordaferrea** [comment]
> Thanks @cordaferrea, I think I'm able to reproduce the problem in my WSL. I will try to provide a solution in the following days.

Thank you owner!  If it is inconvenient, kindly ignore the issue.     

Best Regards,  
Eden

**Comment by gapalomi** [comment]
No problem @cordaferrea. I have published a pre-release version in github with the tentative solution for the problem:
[https://github.com/intel/Edk2Code/releases/tag/pre-1.0.7](https://github.com/intel/Edk2Code/releases/tag/pre-1.0.7)

Can you give it a try?
Here is how to manually install the .vsix in vscode:

![image](https://github.com/intel/Edk2Code/assets/62723455/df8543c0-27d0-41d6-b921-7322101d5d30)

**Comment by cordaferrea** [comment]
Hi @gapalomi ,  

Thanks for such quick repair.! I had try 1.07 version:     
- The bug in Linux Path problem is completely solved.        
- The inf files appear in both .ignore and cscope.files has been solved.       

Really appreciate!  

Best Regards,  
Eden

**Comment by gapalomi** [comment]
Thanks, I will release the change in the following update.
