### ISSUE TITLE
Malformed !ifdef in the code causes error while rebuilding the index database.

### ISSUE THREAD

**Issue by jeffleaming** [intel/Edk2Code#4]
Malformed !ifdef in the code causes error while rebuilding the index database.

![EDK2Code_Error](https://github.com/intel/Edk2Code/assets/51802172/3c03aa5f-c4eb-4997-89c3-0cfaa88345c2)

**Comment by gapalomi** [comment]
Hi @jeffleaming , I have published a pre release version of the extension in github: [https://github.com/intel/Edk2Code/releases/tag/pre-1.0.7](https://github.com/intel/Edk2Code/releases/tag/pre-1.0.7)

This version should show in the problem window whats the line that the parser is not understanding like:
![image](https://github.com/intel/Edk2Code/assets/62723455/76b0d23a-b316-4e97-8620-ecf8722a471b)
I will add more check rules in the future.

This version also will continue the parsing even if that line failed.

Here is how manually can install the pre release version:

![image](https://github.com/intel/Edk2Code/assets/62723455/11a3df11-92b6-4fac-bbdb-f5ad41b8151f)

**Comment by jeffleaming** [comment]
Bingo, looks like it doesn't like comments after the !endif:

![image](https://github.com/intel/Edk2Code/assets/51802172/d59f00b7-ff78-44ba-82ee-8d9657da4407)

**Comment by gapalomi** [comment]
Good we found the problem. Looking at the [DSC documentation](https://tianocore-docs.github.io/edk2-DscSpecification/release-1.28/3_edk_ii_dsc_file_format/32_general_rules.html#32-general-rules) `//` comments are not mentioned
> To append comment information to any item, the comment must start with a hash "#" character.

A quick search in the `.dsc` core files also doesn't show that style of comments.

Im not expert on the edk build tools but looking at the [`DscParser`](https://github.com/tianocore/edk2/blob/master/BaseTools/Source/Python/Ecc/MetaFileWorkspace/MetaFileParser.py#L731C1-L731C33) class of the EDK2 Build tools:

```python
class DscParser(MetaFileParser):
...
[hidden lines]
...
        for Index in range(0, len(Content)):
            Line = CleanString(Content[Index])
            # skip empty line
            if Line == '':
                continue
```

[`CleanString`](https://github.com/tianocore/edk2/blob/master/BaseTools/Source/Python/Common/StringUtils.py#L340) function is being passed without `AllowCppStyleComment` which would allow `//` comment styling.
```python
def CleanString(Line, CommentCharacter=DataType.TAB_COMMENT_SPLIT, AllowCppStyleComment=False, BuildOption=False):
...
    #
    # Replace Edk's comment character
    #
    if AllowCppStyleComment:
        Line = Line.replace(DataType.TAB_COMMENT_EDK_SPLIT, CommentCharacter)
    #
```

**Comment by gapalomi** [comment]
Ah, I see your screenshot is from an `.inf` file. Anyway seems like also the only valid comment style is also `#`
[https://github.com/tianocore-docs/edk2-FdfSpecification/blob/master/2_fdf_design_discussion/22_flash_description_file_format.md#222-comments](https://github.com/tianocore-docs/edk2-FdfSpecification/blob/master/2_fdf_design_discussion/22_flash_description_file_format.md#222-comments)

> The hash "#" character indicates comments in the FDF file. In line comments terminate the processing of a line. In line comments must be placed at the end of the line.
Only BsBaseAddress = 0x0000C1000 in the following example is processed by tools; the remainder of the line is ignored:
BsBaseAddress = 0x0000C100 # set boot driver base address

**Comment by jeffleaming** [comment]
The shot I sent above is from an FDF file...and does compile just fine.

**Comment by gapalomi** [comment]
Sorry, I meant `.fdf` in my previous comment.

I see that even it is not specified in the spec, the [parser for `fdf`](https://github.com/tianocore/edk2/blob/master/BaseTools/Source/Python/GenFds/FdfParser.py#L530) seems to support both comments:

```python
            # check for */ comment end
            elif InComment and not DoubleSlashComment and not HashComment and self._CurrentChar() == TAB_STAR and self._NextChar() == TAB_BACK_SLASH:
                self._SetCurrentCharValue(TAB_SPACE_SPLIT)
                self._GetOneChar()
                self._SetCurrentCharValue(TAB_SPACE_SPLIT)
                self._GetOneChar()
                InComment = False
            # set comments to spaces
            elif InComment:
                self._SetCurrentCharValue(TAB_SPACE_SPLIT)
                self._GetOneChar()
            # check for // comment
            elif self._CurrentChar() == TAB_BACK_SLASH and self._NextChar() == TAB_BACK_SLASH and not self._EndOfLine():
                InComment = True
                DoubleSlashComment = True
            # check for '#' comment
            elif self._CurrentChar() == TAB_COMMENT_SPLIT and not self._EndOfLine() and not InString:
                InComment = True
                HashComment = True
            # check for /* comment start
```

I will add the change in the following release 👍

**Comment by jeffleaming** [comment]
Thanks
