### ISSUE TITLE
Issues with searching for Unicode strings

### ISSUE THREAD

**Issue by EricWeiHuang** [intel/Edk2Code#5]
Type: <b>Bug</b>

An issue arises when searching for Unicode strings, where the search continues indefinitely without producing any results.

Extension version: 1.0.7
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (0.67GB free)|
|Process Argv|--crash-reporter-id a79d526b-0cee-4e53-b7e7-768f32e1e1a1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
gee8j676:31009558
dsvsc021:30996838
0ee40948:31013168

```

</details>

**Comment by gapalomi** [comment]
Hi Eric. Can you document an example to reproduce the issue?

**Comment by EricWeiHuang** [comment]
Hi Gapalomi,

I encountered an issue while searching for a specific Unicode string definition in a project. Initially, the search function worked fine and produced results quickly. However, randomly, there was an issue where the search would continue indefinitely without producing any results, as shown in the attached video. Additionally, an Extension Bisect prompt appeared at the bottom right corner of VS Code. After using Extension Bisect to isolate the extension, it was discovered that closing the Edk2core extension resolved the issue, and everything returned to normal.
<img width="342" alt="VSCode_Extension_Bisect" src="https://github.com/intel/Edk2Code/assets/54828694/b86eaea6-d279-411d-991a-eb92ef7bb191">

My colleague also experienced the same situation.

Abnormal :
https://github.com/intel/Edk2Code/assets/54828694/c27217a6-9532-4d98-b140-96ca25e259d0

Normal :
https://github.com/intel/Edk2Code/assets/54828694/c3795b94-0c3a-460f-bcd3-e8cae8302a66

**Comment by gapalomi** [comment]
Thanks can you share the  **Extension Host** log:
![image](https://github.com/intel/Edk2Code/assets/62723455/636d8a08-a4b9-4f16-9765-3cda267481f0)

**Comment by EricWeiHuang** [comment]
Hi Gapalomi,

Please refer to the attached file.
[20240417_exthost.log](https://github.com/intel/Edk2Code/files/15055967/20240417_exthost.log)

**Comment by gapalomi** [comment]
Thanks Eric. Is this log captured at the moment the failure occurs?
Also, can you capture the log level to **Debug**?
![image](https://github.com/intel/Edk2Code/assets/62723455/14ad8832-e7b6-4842-a69f-abec5a735fd4)
![image](https://github.com/intel/Edk2Code/assets/62723455/00068c5b-35c2-47dc-bab2-03c394548c12)


Thanks

**Comment by EricWeiHuang** [comment]
Hi Gapalomi,

I switched the extension host log to the Debug level
For the screen record and log file please refer to the below.

[Search_Recording](https://aaeon365-my.sharepoint.com/:v:/g/personal/nas_aaeon_com_tw/EWrWenVimtZJo2yG2bP1NXcB2KzOHBq4E0mTieHht6j-aA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=EpV3kr)

[exthost_debug.log](https://github.com/intel/Edk2Code/files/15070183/exthost_debug.log)

Thanks

**Comment by gapalomi** [comment]
Hi Eric, I hasn't been able to reproduce the problem locally. From the exthost_debug.log seems like the last request to ripgrep never came back. 
If you are able to reproduce the issue using just Edk2 code that will help me to debug the issue.
