### ISSUE TITLE
 Edk2Code extension will cause Source Control crash when SCM scanning changed files

### ISSUE THREAD

**Issue by Tody-Guo** [intel/Edk2Code#8]
When we change to Source Control item to see the changed files, when I opened one changed file and opened another file, and reopen last opened file for more times, will cause Source Control extension crash.
When I disabed edk2Code extension, Source Control extension is works normally.

**Comment by gapalomi** [comment]
Hi Tody-Guo. Can you make a minimal workplace example using the EDK2 code to reproduce the problem on my side?
The extension doesn't communicate with SCM services in VSCODE, but it does run a process when EDK files are opened to provide context.

Please include in your instructions to reproduce the issue the version of VSCODE you are using too.

**Comment by Tody-Guo** [comment]
Now I found that scm crash caused by .hfr file when I open .hfr file.

**Comment by gapalomi** [comment]
Hi Tody-Guo,

Could you please provide a minimal workspace example using the EDK2 code to help reproduce the issue on my side? This will greatly assist in diagnosing and resolving the problem. Additionally, please include the version of VSCode you are using.

If possible, could you also add a video or GIF demonstrating the error? This visual aid can be very helpful in understanding the issue more clearly.
